// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Email",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                }
            }
        },
        "/api/user/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User",
                        "name": "entity.EntityUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                }
            }
        },
        "/api/user/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Active",
                        "name": "active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                }
            }
        },
        "/api/user/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get me",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get me",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                }
            }
        },
        "/api/user/password/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update password",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User",
                        "name": "entity.EntityUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                }
            }
        },
        "/api/user/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User",
                        "name": "entity.EntityUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/entity.EntityUser"
                        }
                    }
                }
            }
        },
        "/api/v1/documents": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna uma lista de documentos com filtros opcionais",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Listar documentos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Buscar por nome",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por chave Clicksign",
                        "name": "clicksign_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de documentos",
                        "schema": {
                            "$ref": "#/definitions/dtos.DocumentListResponseDTO"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cria um novo documento usando file_path ou conteúdo base64\nAceita documentos através de file_path (caminho absoluto) ou file_content_base64 (conteúdo em base64)\nPara file_path: file_size e mime_type são obrigatórios\nPara file_content_base64: file_size e mime_type são opcionais (detectados automaticamente)\nTipos suportados: PDF, JPEG, PNG, GIF\nTamanho máximo: 7.5MB após decodificação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Criar documento",
                "parameters": [
                    {
                        "description": "Dados do documento",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.DocumentCreateRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Documento criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/dtos.DocumentResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/documents/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna um documento específico pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Buscar documento por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Documento encontrado",
                        "schema": {
                            "$ref": "#/definitions/dtos.DocumentResponseDTO"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Documento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Atualiza um documento existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Atualizar documento",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.DocumentUpdateRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Documento atualizado",
                        "schema": {
                            "$ref": "#/definitions/dtos.DocumentResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Documento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove um documento do sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Deletar documento",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Documento deletado com sucesso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Documento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/envelopes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get list of envelopes with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "envelopes"
                ],
                "summary": "List envelopes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Clicksign key filter",
                        "name": "clicksign_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.EnvelopeListResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new envelope in Clicksign with optional signatories. When signatories are provided in the request, they will be created along with the envelope in a single atomic transaction. The process maintains backward compatibility - envelopes can still be created without signatories. The response includes the complete raw data returned by Clicksign API for debugging and analysis purposes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "envelopes"
                ],
                "summary": "Create envelope",
                "parameters": [
                    {
                        "description": "Envelope data with optional signatories array. When signatories are provided, the response will include the created signatories with their IDs.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.EnvelopeCreateRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Envelope created successfully. The response includes clicksign_raw_data field with the complete JSON response from Clicksign API (optional field for debugging). If signatories were provided in the request, the response includes the created signatories with their assigned IDs.",
                        "schema": {
                            "$ref": "#/definitions/dtos.EnvelopeResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Validation error - invalid request data, duplicate signatory emails, or unsupported document format",
                        "schema": {
                            "$ref": "#/definitions/dtos.ValidationErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal server error - envelope creation failed or signatory creation failed during transaction",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/envelopes/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get envelope by ID. The response includes clicksign_raw_data field with the complete JSON response from Clicksign API when available (optional field for debugging and analysis).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "envelopes"
                ],
                "summary": "Get envelope",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Envelope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Envelope data with optional clicksign_raw_data field containing raw Clicksign API response",
                        "schema": {
                            "$ref": "#/definitions/dtos.EnvelopeResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/envelopes/{id}/activate": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Activate envelope to start signing process",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "envelopes"
                ],
                "summary": "Activate envelope",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Envelope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.EnvelopeResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/envelopes/{id}/notify": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send notification to envelope signatories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "envelopes"
                ],
                "summary": "Notify envelope",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Envelope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Notification data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.EnvelopeNotificationRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.EnvelopeNotificationResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/envelopes/{id}/requirements": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all requirements for a specific envelope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requirements"
                ],
                "summary": "Get requirements by envelope",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Envelope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Requirements retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/dtos.RequirementListResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Envelope not found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new requirement for an envelope in Clicksign. Requirements define actions (agree, sign, provide_evidence) that signers must complete, along with authentication methods when needed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requirements"
                ],
                "summary": "Create requirement",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Envelope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Requirement data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RequirementCreateRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Requirement created successfully",
                        "schema": {
                            "$ref": "#/definitions/dtos.RequirementResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Validation error - invalid request data or business rule violation",
                        "schema": {
                            "$ref": "#/definitions/dtos.ValidationErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Envelope not found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal server error - requirement creation failed",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/envelopes/{id}/send": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send envelope signatories to Clicksign for processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signatories"
                ],
                "summary": "Send signatories to Clicksign",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Envelope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.SignatoryListResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/envelopes/{id}/signatories": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get list of signatories for a specific envelope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signatories"
                ],
                "summary": "Get signatories by envelope",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Envelope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.SignatoryListResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new signatory for an envelope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signatories"
                ],
                "summary": "Create signatory",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Envelope ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Signatory data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.SignatoryCreateRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.SignatoryResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ValidationErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/requirements/{requirement_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a specific requirement by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requirements"
                ],
                "summary": "Get requirement by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Requirement ID",
                        "name": "requirement_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Requirement retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/dtos.RequirementResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Requirement not found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update a specific requirement (currently only status can be updated)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requirements"
                ],
                "summary": "Update requirement",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Requirement ID",
                        "name": "requirement_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Requirement update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RequirementUpdateRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Requirement updated successfully",
                        "schema": {
                            "$ref": "#/definitions/dtos.RequirementResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Validation error - invalid request data",
                        "schema": {
                            "$ref": "#/definitions/dtos.ValidationErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Requirement not found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a specific requirement",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requirements"
                ],
                "summary": "Delete requirement",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Requirement ID",
                        "name": "requirement_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Requirement deleted successfully"
                    },
                    "404": {
                        "description": "Requirement not found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/signatories/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get signatory by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signatories"
                ],
                "summary": "Get signatory",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Signatory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.SignatoryResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update signatory information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signatories"
                ],
                "summary": "Update signatory",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Signatory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Signatory update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.SignatoryUpdateRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.SignatoryResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ValidationErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete signatory by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signatories"
                ],
                "summary": "Delete signatory",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Signatory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks": {
            "get": {
                "description": "Retorna uma lista de webhooks com filtros opcionais",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Lista webhooks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome do evento",
                        "name": "event_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Chave do documento",
                        "name": "document_key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Chave da conta",
                        "name": "account_key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status do webhook",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Página (padrão: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite por página (padrão: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookListResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "Recebe e processa webhooks enviados pelo Clicksign",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Recebe webhook do Clicksign",
                "parameters": [
                    {
                        "description": "Dados do webhook",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/document/{document_key}": {
            "get": {
                "description": "Retorna webhooks de um documento específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Busca webhooks por document key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chave do documento",
                        "name": "document_key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookListResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/failed": {
            "get": {
                "description": "Retorna webhooks que falharam no processamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Lista webhooks que falharam",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookListResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/pending": {
            "get": {
                "description": "Retorna webhooks que estão pendentes de processamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Lista webhooks pendentes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookListResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/{id}": {
            "get": {
                "description": "Retorna um webhook específico pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Busca webhook por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do webhook",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um webhook do sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Deleta webhook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do webhook",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookProcessResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/{id}/retry": {
            "post": {
                "description": "Tenta reprocessar um webhook que falhou",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Reprocessa webhook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do webhook",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WebhookProcessResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponseDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.DocumentCreateRequestDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Documento para assinatura digital"
                },
                "file_content_base64": {
                    "type": "string",
                    "example": "JVBERi0xLjQKM..."
                },
                "file_path": {
                    "type": "string",
                    "example": "/path/to/document.pdf"
                },
                "file_size": {
                    "type": "integer",
                    "example": 2048576
                },
                "mime_type": {
                    "type": "string",
                    "example": "application/pdf"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3,
                    "example": "Contrato de Prestação de Serviços"
                }
            }
        },
        "dtos.DocumentListResponseDTO": {
            "type": "object",
            "properties": {
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.DocumentResponseDTO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtos.DocumentResponseDTO": {
            "type": "object",
            "properties": {
                "clicksign_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "mime_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.DocumentUpdateRequestDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "draft",
                        "ready",
                        "processing",
                        "sent"
                    ]
                }
            }
        },
        "dtos.EnvelopeCreateRequestDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "approved": {
                    "description": "Indica se o envelope foi aprovado",
                    "type": "boolean"
                },
                "auto_close": {
                    "type": "boolean"
                },
                "deadline_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.EnvelopeDocumentRequest"
                    }
                },
                "documents_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "message": {
                    "type": "string",
                    "maxLength": 500
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "qualifiers": {
                    "description": "Qualificadores para o envelope, como \"sign\", \"agree\", etc.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.EnvelopeRequirementRequest"
                    }
                },
                "remind_interval": {
                    "type": "integer",
                    "maximum": 30,
                    "minimum": 1
                },
                "requirements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.EnvelopeRequirementRequest"
                    }
                },
                "signatories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.EnvelopeSignatoryRequest"
                    }
                },
                "signatory_emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dtos.EnvelopeDocumentRequest": {
            "type": "object",
            "required": [
                "file_content_base64",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "file_content_base64": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                }
            }
        },
        "dtos.EnvelopeListResponseDTO": {
            "type": "object",
            "properties": {
                "envelopes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.EnvelopeResponseDTO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtos.EnvelopeNotificationRequestDTO": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "maxLength": 500
                }
            }
        },
        "dtos.EnvelopeNotificationResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dtos.EnvelopeRequirementRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "agree",
                        "sign",
                        "provide_evidence"
                    ]
                },
                "auth": {
                    "type": "string",
                    "enum": [
                        "email",
                        "icp_brasil"
                    ]
                },
                "document_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "sign"
                    ]
                },
                "signer_id": {
                    "type": "string"
                }
            }
        },
        "dtos.EnvelopeResponseDTO": {
            "type": "object",
            "properties": {
                "auto_close": {
                    "type": "boolean"
                },
                "clicksign_key": {
                    "type": "string"
                },
                "clicksign_raw_data": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deadline_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "documents_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "remind_interval": {
                    "type": "integer"
                },
                "signatories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.SignatoryResponseDTO"
                    }
                },
                "signatory_emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.EnvelopeSignatoryRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "communicate_events": {
                    "$ref": "#/definitions/dtos.SignatoryCommunicateEventsDTO"
                },
                "email": {
                    "type": "string"
                },
                "group": {
                    "type": "integer"
                },
                "has_documentation": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "phone_number": {
                    "type": "string"
                },
                "refusable": {
                    "type": "boolean"
                }
            }
        },
        "dtos.ErrorResponseDTO": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dtos.RequirementCreateRequestDTO": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "agree",
                        "sign",
                        "provide_evidence"
                    ]
                },
                "auth": {
                    "type": "string",
                    "enum": [
                        "email",
                        "icp_brasil"
                    ]
                },
                "document_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "sign"
                    ]
                },
                "signer_id": {
                    "type": "string"
                }
            }
        },
        "dtos.RequirementListResponseDTO": {
            "type": "object",
            "properties": {
                "requirements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.RequirementResponseDTO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtos.RequirementResponseDTO": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "auth": {
                    "type": "string"
                },
                "clicksign_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "document_id": {
                    "type": "string"
                },
                "envelope_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "signer_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.RequirementUpdateRequestDTO": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "completed"
                    ]
                }
            }
        },
        "dtos.SignatoryCommunicateEventsDTO": {
            "type": "object",
            "properties": {
                "document_signed": {
                    "type": "string"
                },
                "signature_reminder": {
                    "type": "string"
                },
                "signature_request": {
                    "type": "string"
                }
            }
        },
        "dtos.SignatoryCreateRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "envelope_id",
                "name"
            ],
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "communicate_events": {
                    "$ref": "#/definitions/dtos.SignatoryCommunicateEventsDTO"
                },
                "email": {
                    "type": "string"
                },
                "envelope_id": {
                    "type": "integer"
                },
                "group": {
                    "type": "integer"
                },
                "has_documentation": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "phone_number": {
                    "type": "string"
                },
                "refusable": {
                    "type": "boolean"
                }
            }
        },
        "dtos.SignatoryListResponseDTO": {
            "type": "object",
            "properties": {
                "signatories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.SignatoryResponseDTO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtos.SignatoryResponseDTO": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "communicate_events": {
                    "$ref": "#/definitions/dtos.SignatoryCommunicateEventsDTO"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "envelope_id": {
                    "type": "integer"
                },
                "group": {
                    "type": "integer"
                },
                "has_documentation": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "refusable": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.SignatoryUpdateRequestDTO": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "communicate_events": {
                    "$ref": "#/definitions/dtos.SignatoryCommunicateEventsDTO"
                },
                "email": {
                    "type": "string"
                },
                "envelope_id": {
                    "type": "integer"
                },
                "group": {
                    "type": "integer"
                },
                "has_documentation": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "phone_number": {
                    "type": "string"
                },
                "refusable": {
                    "type": "boolean"
                }
            }
        },
        "dtos.ValidationErrorDetail": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dtos.ValidationErrorResponseDTO": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ValidationErrorDetail"
                    }
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dtos.WebhookDocumentDTO": {
            "type": "object",
            "required": [
                "account_key",
                "key",
                "status"
            ],
            "properties": {
                "account_key": {
                    "type": "string"
                },
                "attachments": {
                    "type": "array",
                    "items": {}
                },
                "auto_close": {
                    "type": "boolean"
                },
                "block_after_refusal": {
                    "type": "boolean"
                },
                "deadline_at": {
                    "type": "string"
                },
                "downloads": {
                    "$ref": "#/definitions/dtos.WebhookDownloadsDTO"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.WebhookEventDTO"
                    }
                },
                "filename": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "links": {
                    "$ref": "#/definitions/dtos.WebhookLinksDTO"
                },
                "locale": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "path": {
                    "type": "string"
                },
                "preview": {
                    "type": "boolean"
                },
                "remind_interval": {
                    "type": "integer"
                },
                "sequence_enabled": {
                    "type": "boolean"
                },
                "signable_group": {
                    "type": "string"
                },
                "signers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.WebhookSignerDTO"
                    }
                },
                "status": {
                    "type": "string"
                },
                "template": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "uploaded_at": {
                    "type": "string"
                }
            }
        },
        "dtos.WebhookDownloadsDTO": {
            "type": "object",
            "properties": {
                "original_file_url": {
                    "type": "string"
                }
            }
        },
        "dtos.WebhookEventDTO": {
            "type": "object",
            "required": [
                "name",
                "occurred_at"
            ],
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "occurred_at": {
                    "type": "string"
                }
            }
        },
        "dtos.WebhookLinksDTO": {
            "type": "object",
            "properties": {
                "self": {
                    "type": "string"
                }
            }
        },
        "dtos.WebhookListResponseDTO": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "webhooks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.WebhookResponseDTO"
                    }
                }
            }
        },
        "dtos.WebhookProcessResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dtos.WebhookRequestDTO": {
            "type": "object",
            "required": [
                "document",
                "event"
            ],
            "properties": {
                "document": {
                    "$ref": "#/definitions/dtos.WebhookDocumentDTO"
                },
                "event": {
                    "$ref": "#/definitions/dtos.WebhookEventDTO"
                }
            }
        },
        "dtos.WebhookResponseDTO": {
            "type": "object",
            "properties": {
                "account_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "document_key": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "event_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "processed_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dtos.WebhookSignerDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "auths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "birthday": {
                    "type": "string"
                },
                "communicate_by": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "documentation": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "facial_biometrics_enabled": {
                    "type": "boolean"
                },
                "federal_data_validation": {
                    "type": "string"
                },
                "handwritten_enabled": {
                    "type": "boolean"
                },
                "has_documentation": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "latitude": {
                    "type": "string"
                },
                "list_key": {
                    "type": "string"
                },
                "liveness_enabled": {
                    "type": "boolean"
                },
                "longitude": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "official_document_enabled": {
                    "type": "boolean"
                },
                "phone_number": {
                    "type": "string"
                },
                "phone_number_hash": {
                    "type": "string"
                },
                "selfie_enabled": {
                    "type": "boolean"
                },
                "sign_as": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "entity.EntityUser": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 120,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 120,
                    "minLength": 4
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
