version: 2.1

environment:
  CI: true

jobs:
  build-and-test:
    docker:
      - image: 197272534240.dkr.ecr.us-east-1.amazonaws.com/docker-vert:18.06.3-ce-git
        environment:
          DOCKER_REGISTRY: 197272534240.dkr.ecr.us-east-1.amazonaws.com
    working_directory: ~/ms-docsigner/
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 197272534240.dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: Build and Test
          command: |
            cp -f src/.env.sample src/.env
            docker-compose -f docker-compose.yml -f docker-compose.tests.yml down
            docker-compose -f docker-compose.yml -f docker-compose.tests.yml build
            docker-compose -f docker-compose.yml -f docker-compose.tests.yml up -d --no-build
      - run:
          name: Cleanup Containers
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.tests.yml down
          when: always

  build-deliver:
    docker:
      - image: 197272534240.dkr.ecr.us-east-1.amazonaws.com/docker-vert:18.06.3-ce-git
        environment:
          DOCKER_REGISTRY: 197272534240.dkr.ecr.us-east-1.amazonaws.com
    working_directory: ~/ms-docsigner/
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 197272534240.dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: Build Docker Image
          command: |
            export BUILD_VERSION=`echo "$CIRCLE_SHA1" | cut -c 1-8`;
            docker build -t ms-docsigner:"$BUILD_VERSION" ./src
      - run:
          name: Deliver to ECR - Homolog
          command: |
            export BUILD_VERSION=`echo "$CIRCLE_SHA1" | cut -c 1-8`;

            if [ "$CIRCLE_BRANCH" = "homolog" ]
            then
                docker tag ms-docsigner:"$BUILD_VERSION" "$DOCKER_REGISTRY"/ms-docsigner-hml:"$BUILD_VERSION"
                docker tag ms-docsigner:"$BUILD_VERSION" "$DOCKER_REGISTRY"/ms-docsigner-hml:latest
                docker push "$DOCKER_REGISTRY"/ms-docsigner-hml:"$BUILD_VERSION"
                docker push "$DOCKER_REGISTRY"/ms-docsigner-hml:latest
                docker rmi "$DOCKER_REGISTRY"/ms-docsigner-hml:"$BUILD_VERSION"
                docker rmi "$DOCKER_REGISTRY"/ms-docsigner-hml:latest
            fi
      - run:
          name: Deliver to ECR - Production
          command: |
            export BUILD_VERSION=`echo "$CIRCLE_SHA1" | cut -c 1-8`;

            if [ "$CIRCLE_BRANCH" = "master" ]
            then
                docker tag ms-docsigner:"$BUILD_VERSION" "$DOCKER_REGISTRY"/ms-docsigner-prd:"$BUILD_VERSION"
                docker tag ms-docsigner:"$BUILD_VERSION" "$DOCKER_REGISTRY"/ms-docsigner-prd:latest
                docker push "$DOCKER_REGISTRY"/ms-docsigner-prd:"$BUILD_VERSION"
                docker push "$DOCKER_REGISTRY"/ms-docsigner-prd:latest
                docker rmi "$DOCKER_REGISTRY"/ms-docsigner-prd:"$BUILD_VERSION"
                docker rmi "$DOCKER_REGISTRY"/ms-docsigner-prd:latest
            fi

  deploy-to-homolog:
    working_directory: ~/ms-docsigner/
    docker:
      - image: 197272534240.dkr.ecr.us-east-1.amazonaws.com/docker-vert:18.06.3-ce-git
        environment:
          DOCKER_REGISTRY: 197272534240.dkr.ecr.us-east-1.amazonaws.com
    steps:
      - checkout:
          depth: 1
      - run:
          name: Deploy to Homolog Environment
          command: |
            curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
            rm argocd-linux-amd64

            export ARGOCD_SERVER=`echo "$ARGOCD_SERVER"`
            export ARGOCD_AUTH_TOKEN=`echo "$ARGOCD_HOMOLOG_TOKEN"`

            if [ "$CIRCLE_BRANCH" = "homolog" ]
            then
                argocd --grpc-web app actions run ms-docsigner-hml restart --kind Deployment --all
            fi

  deploy-to-production:
    working_directory: ~/ms-docsigner/
    docker:
      - image: 197272534240.dkr.ecr.us-east-1.amazonaws.com/docker-vert:18.06.3-ce-git
        environment:
          DOCKER_REGISTRY: 197272534240.dkr.ecr.us-east-1.amazonaws.com
    steps:
      - checkout:
          depth: 1
      - run:
          name: Deploy to Production Environment
          command: |
            curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
            rm argocd-linux-amd64

            export ARGOCD_SERVER=`echo "$ARGOCD_SERVER"`
            export ARGOCD_AUTH_TOKEN=`echo "$ARGOCD_PRODUCTION_TOKEN"`

            if [ "$CIRCLE_BRANCH" = "master" ]
            then
                argocd --grpc-web app actions run ms-docsigner-prd restart --kind Deployment --all
            fi

workflows:
  version: 2.1
  integration:
    jobs:
      - build-and-test:
          context: environment

      - build-deliver:
          context: environment
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - homolog
                - master

      - deploy-to-homolog:
          context: environment
          requires:
            - build-deliver
          filters:
            branches:
              only:
                - homolog

      - deploy-to-production-approval:
          type: approval
          context: environment
          filters:
            branches:
              only:
                - master
          requires:
            - build-deliver

      - deploy-to-production:
          context: environment
          requires:
            - deploy-to-production-approval
          filters:
            branches:
              only:
                - master
