# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -tags musl -o ./tmp/main ."
# Binary file yields from `cmd`.
bin = "tmp/main"

# Usar eventos do filesystem em vez de polling
poll = false

# Customize binary - sem debug por padrão para performance
full_bin = "./tmp/main"

# Watch these filename extensions.
include_ext = ["go"]

# Ignore these filename extensions or directories.
exclude_dir = [".git", "tmp", "vendor", ".docker", "logs"]

# Watch these directories if you specified.
include_dir = []

# Exclude files.
exclude_file = []

# Aumentar delay para evitar rebuilds excessivos
delay = 2000 # ms

# Stop to run old binary when build errors occur.
stop_on_error = true

# Logs location
log = "logs/air_errors.log"

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color is found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true