// Code generated by MockGen. DO NOT EDIT.
// Source: app/entity (interfaces: IUser)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIUser is a mock of IUser interface.
type MockIUser struct {
	ctrl     *gomock.Controller
	recorder *MockIUserMockRecorder
}

// MockIUserMockRecorder is the mock recorder for MockIUser.
type MockIUserMockRecorder struct {
	mock *MockIUser
}

// NewMockIUser creates a new mock instance.
func NewMockIUser(ctrl *gomock.Controller) *MockIUser {
	mock := &MockIUser{ctrl: ctrl}
	mock.recorder = &MockIUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUser) EXPECT() *MockIUserMockRecorder {
	return m.recorder
}

// GetByMail mocks base method.
func (m *MockIUser) GetByMail(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetByMail indicates an expected call of GetByMail.
func (mr *MockIUserMockRecorder) GetByMail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMail", reflect.TypeOf((*MockIUser)(nil).GetByMail), arg0)
}
