// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecase/user (interfaces: IUsecaseUser)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "app/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIUsecaseUser is a mock of IUsecaseUser interface.
type MockIUsecaseUser struct {
	ctrl     *gomock.Controller
	recorder *MockIUsecaseUserMockRecorder
}

// MockIUsecaseUserMockRecorder is the mock recorder for MockIUsecaseUser.
type MockIUsecaseUserMockRecorder struct {
	mock *MockIUsecaseUser
}

// NewMockIUsecaseUser creates a new mock instance.
func NewMockIUsecaseUser(ctrl *gomock.Controller) *MockIUsecaseUser {
	mock := &MockIUsecaseUser{ctrl: ctrl}
	mock.recorder = &MockIUsecaseUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsecaseUser) EXPECT() *MockIUsecaseUserMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUsecaseUser) Create(arg0 *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIUsecaseUserMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUsecaseUser)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIUsecaseUser) Delete(arg0 *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIUsecaseUserMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUsecaseUser)(nil).Delete), arg0)
}

// GetUser mocks base method.
func (m *MockIUsecaseUser) GetUser(arg0 int) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIUsecaseUserMockRecorder) GetUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIUsecaseUser)(nil).GetUser), arg0)
}

// GetUserByToken mocks base method.
func (m *MockIUsecaseUser) GetUserByToken(arg0 string) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByToken", arg0)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByToken indicates an expected call of GetUserByToken.
func (mr *MockIUsecaseUserMockRecorder) GetUserByToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByToken", reflect.TypeOf((*MockIUsecaseUser)(nil).GetUserByToken), arg0)
}

// GetUsers mocks base method.
func (m *MockIUsecaseUser) GetUsers(arg0 entity.EntityUserFilters) ([]entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", arg0)
	ret0, _ := ret[0].([]entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockIUsecaseUserMockRecorder) GetUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockIUsecaseUser)(nil).GetUsers), arg0)
}

// GetUsersFromIDs mocks base method.
func (m *MockIUsecaseUser) GetUsersFromIDs(arg0 []int) ([]entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersFromIDs", arg0)
	ret0, _ := ret[0].([]entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersFromIDs indicates an expected call of GetUsersFromIDs.
func (mr *MockIUsecaseUserMockRecorder) GetUsersFromIDs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersFromIDs", reflect.TypeOf((*MockIUsecaseUser)(nil).GetUsersFromIDs), arg0)
}

// LoginUser mocks base method.
func (m *MockIUsecaseUser) LoginUser(arg0, arg1 string) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", arg0, arg1)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockIUsecaseUserMockRecorder) LoginUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockIUsecaseUser)(nil).LoginUser), arg0, arg1)
}

// Update mocks base method.
func (m *MockIUsecaseUser) Update(arg0 *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIUsecaseUserMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUsecaseUser)(nil).Update), arg0)
}

// UpdatePassword mocks base method.
func (m *MockIUsecaseUser) UpdatePassword(arg0 int, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockIUsecaseUserMockRecorder) UpdatePassword(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIUsecaseUser)(nil).UpdatePassword), arg0, arg1, arg2, arg3)
}
